### ISSUE TITLE
please tell me the steps, i am using anaconda

### ISSUE THREAD

**Issue by komaldubey003** [satinder147/Face_recognition_attendance_system#2]

**Comment by atulvashisth96** [comment]
try using pycharm

**Comment by satinder147** [comment]
Use https://www.mongodb.com/download-center/v2/community to download mongodb, and you can download anaconda to get almost all the libraries required for running it. For installing tensorflow gpu use https://medium.com/codezillas/step-by-step-guide-to-install-tensorflow-gpu-on-ubuntu-18-04-lts-6feceb0df5c0
