### ISSUE TITLE
no training model found

### ISSUE THREAD

**Issue by Aditya718** [satinder147/Face_recognition_attendance_system#4]
C:\Users\Aditya\Anaconda3\envs\myenv\lib\site-packages\keras\engine\saving.py:292: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
attendance till now is
Rahul 0.0
Gora 0.0
Traceback (most recent call last):
  File "recognizer.py", line 35, in <module>
    test()
  File "recognizer.py", line 25, in test
    test_run=cv2.resize(test_run,(160,160))
cv2.error: OpenCV(3.4.3) C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:4044: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'

**Comment by satinder147** [comment]
you have to place a test image(can be anything) with name "1.jpg" in the project directory

**Comment by Aditya718** [comment]
Thank you sir for the reply, I will update if any further issue arises. It
will be of great help as my final year project is based on this.
