### ISSUE TITLE
cv2.error to run recognier.py

### ISSUE THREAD

**Issue by bl-deepakchawla** [satinder147/Face_recognition_attendance_system#5]
Using TensorFlow backend.
2019-01-02 18:27:34.693326: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
/home/deepak/PycharmProjects/MLProjects/Attendance-using-Face-master/venv/lib/python3.6/site-packages/keras/engine/saving.py:292: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
attendance till now is 
Traceback (most recent call last):
  File "recognizer.py", line 34, in <module>
    test()
  File "recognizer.py", line 24, in test
    test_run = cv2.resize(test_run, (160, 160)).astype('uint8')
cv2.error: OpenCV(3.4.5) /io/opencv/modules/imgproc/src/resize.cpp:3784: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

**Comment by satinder147** [comment]
The error is because opencv can't find the test image. You are supposed to have an test image named "1.jpg" in the root directory of the repo

**Comment by bl-deepakchawla** [comment]
what will be the 1.jpg image

**Comment by satinder147** [comment]
I saw that the first time the model runs, it takes some time. So I ran it on another image and then on the video. So the image can be anything of size (160,160). The image can be of anything. Alternatively, you can remove this function.
