### ISSUE TITLE
Attendance not updated in the mongodb

### ISSUE THREAD

**Issue by bl-deepakchawla** [satinder147/Face_recognition_attendance_system#6]

**Comment by satinder147** [comment]
Check that if you done all the steps correctly.

**Comment by satinder147** [comment]
If you can post a screen shot, it will be easier for me to solve the issue

**Comment by gangubai** [comment]
I am facing also the same problem..


mongo
MongoDB shell version: 3.2.22
connecting to: test
> use new2
switched to db new2
> db.pa.find();
{ "_id" : ObjectId("5c75176e0bab8d8a8f77fa92"), "name" : "Angat", "attendance" : 0 }
{ "_id" : ObjectId("5c756c2efbeb278aaa7d3849"), "name" : "Raunak", "attendance" : 0 }
{ "_id" : ObjectId("5c756c37fbeb278aaa7d384a"), "name" : "Madhura", "attendance" : 0 }
{ "_id" : ObjectId("5c756c41fbeb278aaa7d384b"), "name" : "Maya", "attendance" : 0 }
{ "_id" : ObjectId("5c756c49fbeb278aaa7d384c"), "name" : "Sahil", "attendance" : 0 }

after running the recognizer.py
and csv file is also empty.

**Comment by satinder147** [comment]
change the name of the database in retreive_pymongo_data.py. 
Tip: Try understanding the code and try fixing it on your own (will help you in the longer run)
